#!/usr/bin/zsh

alias cls=clear
alias python='python3'
alias checklist="$HOME/tools/checklist.sh"
alias autocommit="$HOME/tools/commit_tools.sh"
alias cyberchef='python3 -m webbrowser https://gchq.github.io/CyberChef/'
alias shutdown='sudo shutdown now;'
alias ruffix='ruff check . --fix --unsafe-fixes --fixable=ALL'

clipfile(){
    cat $1 | xclip -selection clipboard
}

realias(){
    for z_alias in "${ZALIAS_LOAD[@]}"; do
        source "$ZALIAS/$z_alias"
    done

    if [[ $WORK -eq 1 ]]; then
        for z_alias_work in "$ZALIAS_LOAD_WORK[@]"; do
            source "$ZALIAS/$z_alias_work"
        done
    fi
}

moveinto(){
    mkdir $1
    cd $1
}

setuptemplates(){
    # rm -rf does not follow simlinks
    rm -rf ./.vscode
    rm -rf ./.fttemplates

    # static vsc files/empty dirs
    cp -r "$HOME/vsc_config/vscode" ./.vscode
    mkdir ./.fttemplates
    cp -r "$HOME/vsc_config/templates" ./.vscode/templates

    # versioned files
    setup_versioned $1
}

setup_versioned(){
    if [[ $1 != '' ]]; then
        read_version=$1
    else
        echo "version:"
        read read_version
    fi
    if [[ $read_version -eq '' ]]; then
        echo "no version to set up"
        return
    fi
    versions=('global' "$read_version")
    for version in $versions; do
        setuptemplates_versioned_snippet $version
        setuptemplates_versioned_fttemplates $version
    done
}

setuptemplates_versioned_fttemplates() {
    VERSIONED_DIR="$HOME/vsc_config/fttemplates"
    if [[ -d "$VERSIONED_DIR/$version" ]]; then
        echo "setting up templates version '$version'"
        for file in $VERSIONED_DIR/$version/*; do
            base=$(basename $file)
            if [[ "$base" == '*' ]]; then; continue; fi
            # fttemplates does not like simlinked directories
            cp -r $file "./.fttemplates/$base"
        done
    else
        echo "version '$version' not found"
    fi
}

setuptemplates_versioned_snippet(){
    VERSIONED_DIR="$HOME/vsc_config/snippets"
    if [[ -d "$VERSIONED_DIR/$version" ]]; then
        echo "setting up snippets version '$version'"
        for file in $VERSIONED_DIR/$version/*; do
            base=$(basename $file)
            if [[ "$base" == '*' ]]; then; continue; fi
            ln -s "$file" ./.vscode/$base
        done
    else
        echo "version '$version' not found"
    fi
}

startrebase(){
    current_branch=$(git rev-parse --abbrev-ref HEAD)
    git checkout ${*: -1:1}
    git pull
    git checkout $current_branch
    git rebase ${*: -1:1}
}

listblame(){
    DIR=$1
    IFS="$\n"
    cd "$DIR"
    for i in $(find . -iname "*.py"); do
        LIST="`git blame --line-porcelain "$i" | grep 'author' | sed "s,author,," | tr -d ' '`
        $LIST"
    done
    echo "$LIST" | sort | unic -ic | sort -nr
    unset IFS
}

d () {
    if [[ -n $1 ]]
    then
        dirs "$@"
    else
        dirs -v | head -n 10
    fi
}

for index ({1..9}) alias "$index"="cd -${index}"; unset index
PATH="$PATH:/home/kenzo/Desktop/tools:~/.local/bin"
