#!/usr/bin/zsh

alias cls=clear
alias python='python3'
alias checklist="$HOME/tools/checklist.sh"
alias autocommit="$HOME/tools/autocommit.py"
alias new_autocommit="$HOME/tools/new_autocommit.sh"
alias cyberchef='python3 -m webbrowser https://gchq.github.io/CyberChef/'
alias shutdown='sudo shutdown now;'
alias ruffix='ruff check . --fix --unsafe-fixes --fixable=ALL'
alias lh='ls -lh'

clipfile(){
    cat $1 | xclip -selection clipboard
}

realias(){
    # force reloading env if those changed
    source ~/.zshenv
    for z_alias in "${ZALIAS_LOAD[@]}"; do
        source "$ZALIAS/$z_alias"
    done

    if [[ $WORK -eq 1 ]]; then
        for z_alias_work in "$ZALIAS_LOAD_WORK[@]"; do
            source "$ZALIAS/$z_alias_work"
        done
    fi
}


# git stuff
startrebase(){
    current_branch=$(git rev-parse --abbrev-ref HEAD)
    git checkout ${*: -1:1}
    git pull
    git checkout $current_branch
    git rebase ${*: -1:1}
}

listblame(){
    DIR=$1
    IFS="$\n"
    cd "$DIR"
    for i in $(find . -iname "*.py"); do
        LIST="`git blame --line-porcelain "$i" | grep 'author' | sed "s,author,," | tr -d ' '`
        $LIST"
    done
    echo "$LIST" | sort | unic -ic | sort -nr
    unset IFS
}

#directory traversal
# mkdir and cd
moveinto(){
    mkdir $1
    cd $1
}

## projectroot
mark_projectroot(){
    if [[ $1 != '' ]]; then
        touch "$1/.projectroot"
        return
    fi
    touch ".projectroot"
}

mv_projectroot(){
    curdir=$(pwd)
    while [[ ! -f .projectroot ]]; do
        if [[ $(pwd) == '/' ]]; then
            echo "Project Root not found"
            cd $curdir
            return 1
        fi
        cd ..
    done
}

projectroot(){
    # get the relative path to projectroot
    curdir=$(pwd)
    has_moved=0
    while [[ ! -f .projectroot ]]; do
        if [[ $(pwd) == '/' ]]; then
            echo -n '.'
            cd $curdir
            return 1
        fi
        # makes using as $(projectroot)/some/sub/dir cleaner
        if [[ $has_moved == 1 ]]; then
            echo -n '/'
        fi
        echo -n '..'
        cd ..
        has_moved=1
    done
    if [[ $(pwd) == $curdir ]]; then
        echo -n '.'
    fi
    cd $curdir
}

## generic traversal
d() {
    if [[ -n $1 ]]
    then
        dirs "$@"
    else
        dirs -v | head -n 10
    fi
}

for index ({1..9}) alias "$index"="cd -${index}"; unset index
PATH="$PATH:~/tools:~/.local/bin"
