#!/usr/bin/bash
alias cls=clear
alias python='python3'
alias checklist='~/config/checklist.sh'
alias autocommit='~/config/commit_tools.sh'
alias cyberchef='python3 -m webbrowser https://gchq.github.io/CyberChef/'
alias shutdown='sudo shutdown now;'
alias realias='source ~/.aliases && source ~/.alias_extra'


moveinto(){
    mkdir $1
    cd $1
}

setuptemplates(){
    cp -r ~/config/vsc_config/vscode ./.vscode
    cp -r ~/config/vsc_config/fttemplates ./.fttemplates
    cp -r ~/config/vsc_config/templates ./.vscode/templates
}

startrebase(){
    current_branch=$(git rev-parse --abbrev-ref HEAD)
    git checkout ${*: -1:1}
    git pull
    git checkout $current_branch
    git rebase ${*: -1:1}
}

listblame(){
    DIR=$1
    IFS="$\n"
    cd "$DIR"
    for i in $(find . -iname "*.py"); do
        LIST="`git blame --line-porcelain "$i" | grep 'author' | sed "s,author,," | tr -d ' '`
        $LIST"
    done
    echo "$LIST" | sort | unic -ic | sort -nr
    unset IFS
}

d () {
    if [[ -n $1 ]]
    then
        dirs "$@"
    else
        dirs -v | head -n 10
    fi
}

for index ({1..9}) alias "$index"="cd -${index}"; unset index
PATH="$PATH:/home/kenzo/Desktop/tools:~/.local/bin"
