#!/usr/bin/bash

alias rundb="psql -h db -U postgres"
alias rundebug="runserver --debugpy --debugpy-wait-for-attach"
alias dlbackup="rm backup.zip; curl -o backup.zip"

cleandocker(){
    for i in {13..18}; do
        docker rmi $(docker image list "registry.gitlab.com/apertoso/docker/odoo/odoo${i}e" | awk '{print $1":"$2}' | grep registry) 2> /dev/null
    done
    docker system prune -f --volumes --all
}

cleanup(){
    curdir=$(pwd)
    if [[ ! mv_projectroot ]]; then
        cleandocker
        cd $curdir
        return
    fi
    rootdir=$(pwd)
    for dir in ./repos/*; do
        cd $dir
        git gone
        cd $rootdir
    done
    cd addons-extra
    find ./ -type l -exec file {} \;  | awk '/: broken/{print substr($1,3, length($1)-3)}' | xargs unlink
    cleandocker
    cd $curdir
}

newproject(){
    echo "Creating directory $1"
    moveinto $1
    mark_projectroot
    echo "Setting up project"
    projectsetup --init "$2"
    echo "Getting latest database"
    dbrestore --drop --s3
    echo "Bootstrapping custom templates"
    setuptemplates
    bootstrap_configs
}

resetserver(){
    projectsetup -R
    projectsetup --update-all
    sleep 1
    if [ "$#" -eq 1 ]; then
        echo "restoring from zip file"
        dbrestore --drop --zip $@
    else
        echo "restoring from s3"
        dbrestore --drop --s3
    fi
    dbrestore --post
    cleandocker
}

gitsetbases(){
    projectsetup -r
    curdir=$(pwd)
    mv_projectroot
    if [[ ! -f .instance_data.json ]]; then
        cd $curdir
        return
    fi
    resetcmd=$(cat .instance_data.json | python -c 'import sys, json; print("\n".join([f"cd repos/{k}\ngit checkout {v["branch"]}\ngit pull\ncd ../.." for k,v in json.load(sys.stdin)["branches"].items()]))')
    $SHELL -c $resetcmd
    cd $curdir
}

link(){
    curdir=$(pwd)
    # our system requires relative symlinks
    gitroot=$(basename $(git rev-parse --show-toplevel))
    if mv_projectroot; then
        proot=$(pwd)
        for item in $@; do
            cd addons-extra
            ln -s "../repos/$gitroot/$item" || true
            cd $proot
        done
    fi
    cd $curdir
}

mkbranch(){
    gitsetbases
    echo "version:"
    read version
    echo "name:"
    read name
    git checout -b "$version-T00000-name"
}

bump(){
    sed -i "/version/c\    'version': '$1.0.1.0.0'," */__manifest__.py
    sed -i "/installable/c\    'installable': False," */__manifest__.py
}

