#!/usr/bin/bash

files=('.aliases' '.alias_extra' '.ssh/config' '.gitconfig' '.zshrc' '.vimrc')
fdirs=('.sshrc.d' 'config')
for file in "${files[@]}"; do
    cp "$HOME/${file}" $file
done

for fdir in "${firds[@]}"; do
    rm -rf $fdir
    cp -r "$HOME/$fdir" $fdir
done

cp .zshrc .sshrc.d/.zshrc
code --list-extensions > vsc_extensions.txt
