#!/usr/bin/bash

CONFIG_ROOT=$(git rev-parse --show-toplevel)

bash "$CONFIG_ROOT/install/base_installers"
bash "$CONFIG_ROOT/install/setup_stage2"
git remote set-url origin git@github.com:kenzo-staelens/linux_configuration.git
