#!/usr/bin/bash

export ZDOTDIR="$HOME/zsh"
export ZALIAS="$ZDOTDIR/alias"

mkdir -p "$ZDOTDIR"
mkdir -p "$ZALIAS"

CONFIG_ROOT=$(git rev-parse --show-toplevel)

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended

# needs validate
cd "$ZALIAS"
unlink base || true
unlink system || true
rm base || true
rm system || true
ln -s "$CONFIG_ROOT/aliases/base"
ln -s "$CONFIG_ROOT/aliases/system"
ln -s "$CONFIG_ROOT/aliases/odoo"

cd "$HOME/.ssh"
unlink config || true
rm config || true
ln -s "$CONFIG_ROOT/.ssh/config"

# git setup
cd "$HOME"
unlink .gitconfig || true
rm .gitconfig || true
unlink .gitconfig_work || true
rm .gitconfig_work
ln -s "$CONFIG_ROOT/.gitconfig"
ln -s "$CONFIG_ROOT/work/.gitconfig_work"

# vim
unlink .vimrc || true
rm .vimrc || true
ln -s "$CONFIG_ROOT/.vimrc"

# sshrc
unlink .sshrc.d || true
rm -r .sshrc.d || true
ln -s "$CONFIG_ROOT/.sshrc.d"

# custom tools
unlink tools || true
rm -r tools || true
ln -s "$CONFIG_ROOT/tools"

# zsh setup
unlink .zshenv || true
rm .zshenv || true
ln -s "$CONFIG_ROOT/zsh_config/.zshenv"

cd "$ZDOTDIR"
unlink .zshrc || true
unlink zsh_completion || true
unlink plugins || true
rm .zshrc || true
rm zsh_completion || true
rm -r plugins || true
ln -s "$CONFIG_ROOT/zsh_config/zsh/.zshrc"
ln -s "$CONFIG_ROOT/zsh_config/zsh/zsh_completion"
ln -s "$CONFIG_ROOT/plugins"

cd "$ZDOTDIR/ohmyzsh/custom/themes"
unlink kali-like.zsh-theme || true
rm kali-like.zsh-theme || true
ln -s "$CONFIG_ROOT/zsh_config/zsh/kali-like.zsh-theme"

if [ ! -f "$ZALIAS/.aliases" ]; then
    echo '#!/usr/bin/bash' > "$ZALIAS/.aliases"
fi

while read p; do
    code --install-extension "$p" --force
done < "$CONFIG_ROOT/vsc_extensions.txt"

cd "$HOME/Code/User"
unlink settings.json || true
rm settings.json || true
ln -s "$CONFIG_ROOT/vsc_config/settings.json"

cd "$HOME" ln -s "$CONFIG_ROOT/vsc_config"
